services:
  web:
    build: ./apache
    hostname: web
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./prestashop:/app
      - ./apache/prestashop.conf:/etc/apache2/sites-enabled/prestashop.conf
      - ./apache/entrypoint.sh:/entrypoint.sh
      - ./certs:/.certs
      - ./logs:/logs
    env_file:
      - .env.prod
