services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/prestashop-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./prestashop:/app
      - ./logs:/logs
      # - ./nginx/php.ini:/etc/php/8.2/fpm/php.ini

    ports:
      - '80:80'
      - '443:443'

  web:
    build: ./nginx
    hostname: web

    volumes:
      - ./prestashop:/app
      - ./certs:/.certs
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./logs:/logs
    env_file:
      - .env.prod
    networks:
      rede_test:
        aliases:
          - adrian.lan
          - www.adrian.lan
          - tech.a24adrianbr.tech
