services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/prestashop-nginx.conf:/etc/nginx/conf.d/prestashop.conf
      - ./prestashop:/app
      - ./certs:/.certs
      - ./logs:/logs
      # - ./nginx/php.ini:/etc/php/8.2/fpm/php.ini

    ports:
      - '80:80'
      - '443:443'

  web:
    build: ./nginx
    hostname: web
    restart: always
    volumes:
      - ./prestashop:/app
      - ./certs:/.certs
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./logs:/logs
    env_file:
      - .env.prod
