services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/prestashop-nginx.conf:/etc/nginx/conf.d/prestashop.conf
      - ./prestashop:/app
      - ./certs:/.certs
      - ./logs:/logs
    depends_on:
      - web
    ports:
      - '8000:80'
      - '443:443'
    networks:
      rede_test:
        aliases:
          - adrian.lan
          - www.adrian.lan
          - tech.a24adrianbr.tech
  web:
    build: ./nginx
    hostname: web
    volumes:
      - ./prestashop:/app
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./logs:/logs
      # - ./nginx/php.ini:/etc/php/8.2/fpm/php.ini
    environment:
      DB_HOST: db1
      MYSQL_USER: user
      MYSQL_PASSWORD: userpw123.
      MYSQL_DATABASE: db
    networks:
      rede_test:
    depends_on:
      - db1

  db1:
    image: mysql:latest
    restart: always
    env_file:
      - .env.dev
    volumes:
      - db1:/var/lib/mysql
      - ./backup:/backup
    networks:
      rede_test:

  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority
    networks:
      rede_test:
    depends_on:
      - web

volumes:
  db1:

networks:
  rede_test:
