<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBiakzCa\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBiakzCa/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerBiakzCa.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerBiakzCa\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerBiakzCa\appAppKernelProdContainer([
    'container.build_hash' => 'BiakzCa',
    'container.build_id' => 'dfaf6fff',
    'container.build_time' => 1745320541,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBiakzCa');
